UpdateShipmentRequest, UpdateShipmentSRequest, InsertShipmentSRequest + tests
DeliveryMatch/api-library pull request #10
Opened 2022-04-24 19:03 UTC by Rebecca-v-L

Kan alvast reviewed worden. Note: https://github.com/DeliveryMatch/dmengine/issues/8709#issuecomment-1107836916 -> pas ik toe wanneer fix gevonden is.

Edit: Naar dev_rebecca branch veranderd om te mergen i.p.v dev branch i.v.m InsertShipmentRequest 'missing weight' issue

2022-04-25 08:38 UTC, koen-dm commented on src/dto/requests/UpdateShipmentRequest.php
> +    private ?Customer $customer;
Hier mis je nog wat velden en `Client` is een verplicht veld. https://engine4.delmatch.eu/documentation#/operations/fb912b1b4cd40bd0d32d782f80052ad1

2022-04-25 08:39 UTC, koen-dm commented on src/dto/requests/UpdateShipmentsRequest.php
> +}
Zelfde als met `insertShipments`

2022-04-25 08:43 UTC, koen-dm commented
@Rebecca-v-L Je kunt gewoon nieuwe commits blijven toevoegen in deze PR, die komen er dan automatisch bij te staan. Kan je ook even het merge conflict oplossen?

2022-04-25 09:45 UTC, Rebecca-v-L commented on src/dto/requests/InsertShipmentRequest.php
> +    private ?Package $packages;
Klopt, refactor heeft die niet goed mee genomen zo te zien. Ik heb 'm aangepast.

2022-04-25 09:49 UTC, Rebecca-v-L commented on src/dto/requests/InsertShipmentsRequest.php
> +}
Is het niet gewoon een array van meerdere shipments ? Kan je anders even een json sturen, het vb op de api van InsertShipment & InsertShipments zijn namelijk hetzelfde

2022-04-25 09:49 UTC, Rebecca-v-L commented
@koen-dm Zal ik doen

2022-04-25 10:33 UTC, koen-dm commented on src/dto/requests/InsertShipmentsRequest.php
> +}
`insertShipments` gaat niet over het insturen van een array van shipments. Het klopt dat het idd exact hetzelfde request is als `insertShipment`. `insertShipments` gaat over multi carrier zendingen. Bijvoorbeeld package 1 moet met postNL en package 2 moet met GLS

2022-04-25 10:37 UTC, koen-dm commented on src/dto/requests/InsertShipmentsRequest.php
> +}
`insertShipments` gaat niet over het insturen van een array van shipments. Het klopt dat het idd exact hetzelfde request is als `insertShipment`. `insertShipments` gaat over multi carrier zendingen. Bijvoorbeeld package 1 moet met postNL en package 2 moet met GLS. En omdat het uit 2 verschillende vervoerders wordt verstuurd worden er bij ons intern 2 shipments aangemaakt.

Had een tijdje terug een stukje documentatie gemaakt voor een partij die dit ging gebruiken. Misschien heb je er wat aan.
[insertShipmentsManual.pdf](https://github.com/DeliveryMatch/api-library/files/8553740/insertShipmentsManual.pdf)

2022-04-25 14:07 UTC, Rebecca-v-L commented
@koen-dm Zou jij even naar de index kunnen gaan en de 2 methodes runnen die daar klaar staan (getShipments & updateShipment). Ik krijg steeds de onderstaande errors
getShipments:
   failure: No start and/or end date found 
   
updateShipments: 
 Undefined array key "client"
 Uncaught TypeError: Cannot assign null to property UpdateShipmentRequest::$client of type Client

2022-04-26 10:59 UTC, koen-dm requested changes
Kan je overal weer normale constructors maken? Dat maakt het wat makkelijker met auto completion. 

Veder denk ik dat inherentence toch niet de oplossing is omdat bij de update varianten er veel nullable parameters zijn.

2022-04-26 10:59 UTC, koen-dm commented on src/dto/requests/GetShipmentsRequest.php
> +class GetShipmentsRequest
Je mist hier `JsonSerializable`

2022-04-26 10:59 UTC, koen-dm commented on src/dto/requests/InsertShipmentRequest.php
> +    protected Shipment|ShipmentUpdate $shipment;
Kan alleen in php 8

2022-04-26 11:10 UTC, koen-dm commented
@Rebecca-v-L Het is ook wel handig om xDebug op te zetten voor als je dat nog niet had gedaan.

2022-04-26 15:05 UTC, Rebecca-v-L commented on src/dto/requests/GetShipmentsRequest.php
> +    }
@koen-dm Ik zal het aanpassen en de union types eruit halen

2022-04-26 15:22 UTC, koen-dm commented on src/dto/requests/GetShipmentsRequest.php
> +    }
@Rebecca-v-L hoeft niet. Zie php docs. https://www.php.net/manual/en/jsonserializable.jsonserialize.php 

Had ook zelf nog even getest en werkte bij mij

2022-04-26 15:27 UTC, Rebecca-v-L commented on src/dto/requests/GetShipmentsRequest.php
> +    }
@koen-dm ik ga het aanpassen

2022-04-28 07:35 UTC, koen-dm requested changes

2022-04-28 07:35 UTC, koen-dm commented on index.php
> +$shipment = new GetShipmentsRequest(array('dateFrom' => "2022-02-20", 'dateTo' => "2022-02-25", "status" => null, "channel" => null));
Misschien de channel als parameter voor het maken van een nieuwe `DeliveryMatchClient`.

2022-04-28 07:35 UTC, koen-dm commented on src/dto/general/Warehouse.php
> +    }
`$stockdate` formatten naar YYYY-MM-DD voor in de JSON

2022-04-28 07:35 UTC, koen-dm commented on src/dto/requests/GetShipmentsRequest.php
> +                'dateTo' => $this->getDateTo()->format("YYY-MM-DD"),
Zo gaat het niet werken denk ik. Zie: https://www.php.net/manual/en/datetime.format.php. Volgensmij moet het `Y-m-d` zijn

2022-04-28 17:10 UTC, Rebecca-v-L commented on index.php
> +$shipment = new GetShipmentsRequest(array('dateFrom' => "2022-02-20", 'dateTo' => "2022-02-25", "status" => null, "channel" => null));
@koen-dm hoe bedoel je precies ?

1) `new DeliveryMatchClient($_SERVER["CLIENT_ID"], $_SERVER["API_KEY"], $_SERVER["URL"], new Client(...))`
2) `new DeliveryMatchClient($_SERVER["CLIENT_ID"], $_SERVER["API_KEY"], $_SERVER["URL"], $_CHANNEL['NAME'])`

Of iets anders ?

2022-04-28 17:11 UTC, Rebecca-v-L commented on src/dto/requests/GetShipmentsRequest.php
> +                'dateTo' => $this->getDateTo()->format("YYY-MM-DD"),
@koen-dm klopt, moest ik nog fixen :)

2022-04-29 15:43 UTC, Rebecca-v-L commented
@koen-dm Sommige functies returnen een exception ookal zijn ze eigenlijk succesvol 
e.g:
getLabel: DeliveryMatchApiLibrary\exceptions\DeliveryMatchException : booked: Shipment label(s) found
updateShipment: DeliveryMatchApiLibrary\exceptions\DeliveryMatchException : booked: Shipment succesfully saved
etc

Volgens mij is dit niet echt de bedoeling, zou je daar even naar kunnen kijken/het kunnen oplossen ?

2022-05-02 09:17 UTC, koen-dm commented
@Rebecca-v-L onze api geeft altijd een status 200 terug. En in sommige gevallen geeft een status mee terug, en in andere gevallen niet. Beetje onhandig.

Hoe ik het zou oplossen (geen mooie oplossing btw, maar kan niet op iets beters komen haha):
1. uitzoeken welke endpoints een status terug geven en checken of deze `status 7` geven. (volgensmij betekend dit success maar moet je even checken)
2. Voor de andere endpoints kijken waaraan je kan zien of het gelukt is of niet. Bijvoorbeeld: `getShipment` geeft geen code terug bij een succesvol response, maar als het response een shipment met id terug geeft kan je er vanuit gaan dat dit goed is gegaan.

Wel belangrijk dat je dit even goed unit test

2022-05-02 09:20 UTC, koen-dm requested changes

2022-05-02 09:20 UTC, koen-dm commented on src/DeliveryMatchClient.php
Checks toevoegen genoemd in https://github.com/DeliveryMatch/api-library/pull/10#issuecomment-1114653363

2022-05-02 09:20 UTC, koen-dm commented on src/dto/general/Shipment.php
> +    protected ?string $deliveryTimeTo;
Hiervoor ook een `DateTime` gebruiken

2022-05-02 09:20 UTC, koen-dm commented on src/dto/general/Shipment.php
> +                'deliveryTimeTo' => $this->getDeliveryTimeTo(),
`DateTime` formatteren

2022-05-02 09:23 UTC, koen-dm commented on index.php
> +$shipment = new GetShipmentsRequest(array('dateFrom' => "2022-02-20", 'dateTo' => "2022-02-25", "status" => null, "channel" => null));
@Rebecca-v-L optie 2. Alleen hoeft channel geen environment variabel te zijn. Misschien ook iets van een default waarde geven als `DeliveryMatch API Library`

<img width="567" alt="image" src="https://user-images.githubusercontent.com/55694567/166213002-b7e71899-2369-4714-9f5c-0bfc14c68667.png">

2022-05-02 10:13 UTC, Rebecca-v-L commented
@koen-dm ik dacht al dat we zoiets zouden moesten gaan toepassen. Niet een hele mooie oplossing idd maar het is even niet anders haha. Ik zal het regelen

2022-05-02 10:34 UTC, Rebecca-v-L commented on index.php
> +$shipment = new GetShipmentsRequest(array('dateFrom' => "2022-02-20", 'dateTo' => "2022-02-25", "status" => null, "channel" => null));
@koen-dm hoe had jij die default waarde in gedachte ? Vb standaard deze op 66 zetten oid ? En wat bedoel je met `DeliveryMatch API Library` ?

2022-05-11 16:27 UTC, koen-dm reviewed
Ziet er goed uit

2022-05-13 18:37 UTC, Rebecca-v-L commented
@koen-dm All yours !

2022-05-18 09:34 UTC, merged