Object auto-completion & small test fixes
DeliveryMatch/api-library pull request #11
Opened 2022-05-18 12:36 UTC by Rebecca-v-L

2022-05-18 12:41 UTC, koen-dm requested changes
Je hebt nu het request object als return object gemaakt. Maar de response van de api is natuurlijk anders dan de request

2022-05-18 12:45 UTC, Rebecca-v-L commented
@koen-dm Dacht dat je dat bedoelde op Slack. Je wil dus dat ik per request een response class maak en deze return ?

2022-05-18 12:51 UTC, koen-dm commented
@Rebecca-v-L Ja. Maar dat kan vrij simpel met een tool zie: https://github.com/DeliveryMatch/dmengine/issues/8709#issuecomment-1129796321

2022-05-18 13:08 UTC, Rebecca-v-L commented
@koen-dm Ik snap 'm nu, komt goed

2022-05-25 08:11 UTC, koen-dm requested changes
Nog een paar kleine dingetjes.

Ook moet je even checken of strings automatisch worden omgezet naar `Date` & `DateTime` 

```php
    public Date $datePickup;
    public Date $dateDelivery;
```

2022-05-25 08:11 UTC, koen-dm commented on src/dto/responses/GetShipmentResponse.php
> +    public array $barcodes;
Misschien beter als we er `string[]` van maken

2022-05-25 08:11 UTC, koen-dm commented on src/dto/general/response/getShipment/SenderAddressResponse.php
> +    public Date $address1;
Foutje denk ik ;)

2022-05-25 09:38 UTC, Rebecca-v-L commented on src/dto/responses/GetShipmentResponse.php
> +    public array $barcodes;
@koen-dm Goed idee, ga ik doen

2022-05-25 09:39 UTC, Rebecca-v-L commented on src/dto/general/response/getShipment/SenderAddressResponse.php
> +    public Date $address1;
@koen-dm haha die is er nog tussen geslopen van de tool, dacht dat ik ze allemaal had gevonden. Ik pas 'm aan ;)

2022-05-25 09:49 UTC, Rebecca-v-L commented
@koen-dm alle `Date` & `DateTime` worden strings dus ik ga die aanpassen

2022-05-25 13:26 UTC, koen-dm requested changes
Je kan die `string` naar `DateTime` nog wel fixen.

Voorbeeldje:
```php
public function exampleRequest(Request $request)
{
  $response = $this->connectApi("exampleRequest", $insertShipmentRequest);
  // Let op wel nog even goede input dateformat gebruiken
  $response->date = DateTime::createFromFormat("'d/m/Y", $response->date)

  return $response;
}

2022-05-25 13:26 UTC, koen-dm commented on src/dto/general/response/getShipments/GetShipmentsShipmentsResponse.php
> +use Cassandra\Date;
Verkeerde date type

2022-05-25 13:26 UTC, koen-dm commented on src/dto/general/response/updateShipment/DeliveryResponse.php
> +use Cassandra\Date;
Hier ook

2022-05-25 13:26 UTC, koen-dm commented on src/dto/general/response/updateShipment/PickupResponse.php
> +use Cassandra\Date;
Hier ook

2022-05-25 16:05 UTC, Rebecca-v-L commented
@koen-dm Wat dacht je van een recursion functie i.p.v per datetime variable.

```
public function stringToDateTime($result) {
        foreach($result as $key => &$value)
        {
            if (!is_array($value))
            {
                if(strpos($key, 'date')) {
                    $value = DateTime::createFromFormat("Y-m-d", $value);
                }
                if(strpos($key, 'time')) {
                    $value = DateTime::createFromFormat("H:i", $value);
                }
            } else {
                $this->stringToDateTime($value);
            }
        }

        return $result;
    }
```

2022-05-25 17:28 UTC, koen-dm commented
@Rebecca-v-L Kan idd werken, maar dan krijg je wel een lange if statement. 

```php

if(strpos($key, 'date')) {
                    $value = DateTime::createFromFormat("Y-m-d", $value);
                }
                if(strpos($key, 'time')) {
                    $value = DateTime::createFromFormat("H:i", $value);
                }

```

Elk veld wat dan een `datetime` moet zijn moet je natuurlijk in die for loop zetten. Beide opties kunnen.

2022-05-25 19:20 UTC, Rebecca-v-L commented
@koen-dm denk dat de recursion ietsjes netter is ondanks de if statements dan tig keer per methode. 
```
$response->date = DateTime::createFromFormat("Y-m-d", $response->date);
$response->array->date = DateTime::createFromFormat("Y-m-d", $response->array->date);
etc...
```
En zo checkt die gewoon de hele response i.p.v alleen maar de waardes die mee worden gegeven.  Heeft voor- en nadelen, dus laat maar weten of je liever d.m.v recursion of per variable wil

2022-05-26 12:08 UTC, koen-dm approved these changes

2022-07-01 14:41 UTC, merged